### ISSUE TITLE
tests that fail with farff but work with RWeka

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/farff#12]
In https://github.com/mlr-org/farff/pull/11, I added a test with a few ARFF files from OpenML that can be read by RWeka but not with farff. The test is skipped on travis, but should run when you use `devtools::check()` on your local machine.

**Comment by berndbischl** [comment]
? Why would it run locally?

**Comment by berndbischl** [comment]
You mean it is executed, but locally throws visible errors?

**Comment by giuseppec** [comment]
Yes, I meant that it is just executed locally and throws visible errors. If you want to see the errors on travis, you should remove the `!` in the first line of the `test_reader.R` file.

**Comment by jakobbossek** [comment]
Regarding Giuseppes pull request: datasets 119 and 572 can be parsed now. datasets 350, 386, 391, 397, 401 are is sparse format. We do not support that for the moment and throw an error (see #4).
Closing for now.
