### ISSUE TITLE
Quoted strings in nominal values

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/farff#14]
ds = getOMLDataSet(71) # no problems with RWeka
setOMLConfig(arff.reader = "farff")
ds = getOMLDataSet(71)
> Data '71' file 'description.xml' found in cache.
> Data '71' file 'dataset.arff' found in cache.
> Fehler in consume(x, "^\\s*\\}\\s*", no.match.error = TRUE) :
>  Error while parsing factor levels in line:
> @attribute carbon {'\'B1of3\'','\'B2of3\'','\'B3of3\''}

**Comment by jakobbossek** [comment]
Might be related to #10.

**Comment by berndbischl** [comment]
it not related to 10. I occurs also with readr and is a bug when we parse the header / factor levels

**Comment by berndbischl** [comment]
This works now. I have added a similar unit test, converted from the same data did 71. Because that data set is just too large for a repeated test.
