### ISSUE TITLE
factors with levels T,F are converted to logical (like RWeka)

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/farff#22]
We maybe should add an option to deactivate this converting to logical
(I am referring to https://github.com/mlr-org/farff/commit/8e4ed73c0cc70ae3baf5e3c9ca6699aed802f8c3)

**Comment by berndbischl** [comment]
Why? Give a reason.  Mine is to be compatible to rweka.

**Comment by giuseppec** [comment]
Well, modelling with logicals is not always possible and they have to be converted into factors or numerics anyway. I had a problem with this logicals in OpenML, but I fixed it in https://github.com/openml/r/commit/ff96c84eef4b69bac17f1bb776d62f6285f10a1c (don't worry, I'll add a test for this in OpenML) so I don't care anymore. We can close this if you want.

**Comment by berndbischl** [comment]
we can maybe later add such an option. should be easy.

**Comment by giuseppec** [comment]
Yes, I can do this after we finished v1.0.

**Comment by berndbischl** [comment]
we doc this for now

**Comment by jakobbossek** [comment]
Added parameter `convert.to.logicals` to `readARFF` with default value `TRUE`.
Closing
