### ISSUE TITLE
Error parsing file

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/farff#25]
```splus
getOMLRun(536902)
```
fails with the following error:
```
Warnung: 49 parsing failures.
row col               expected                                    actual
  1  X1 no trailing characters NA43"Iris-setosa""Iris-setosa"100
  2  X1 no trailing characters NA76"Iris-versicolor""Iris-versicolor"010
  3  X1 no trailing characters NA49"Iris-setosa""Iris-setosa"100
  4  X1 no trailing characters NA85"Iris-versicolor""Iris-versicolor"010
  5  X1 no trailing characters NA134"Iris-virginica""Iris-virginica"001
... ... ...................... .........................................
.See problems(...) for more details.
Fehler in `colnames<-`(`*tmp*`, value = header$col.names) :
  Attribut 'names' [8] muss dieselbe Länge haben wie der Vektor [1]
Zusätzlich: Warnmeldung:
Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two.
```

This is the content of the arff file:
@relation 'run$predictions'
@attribute 'repeat' numeric
@attribute 'fold' numeric
@attribute 'row_id' numeric
@attribute 'prediction' {'Iris-setosa','Iris-versicolor','Iris-virginica'}
@attribute 'truth' {'Iris-setosa','Iris-versicolor','Iris-virginica'}
@attribute 'confidence.Iris-setosa' numeric
@attribute 'confidence.Iris-versicolor' numeric
@attribute 'confidence.Iris-virginica' numeric
@data
0 ? 43 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 76 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 49 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 85 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 134 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 122 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 110 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 130 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 82 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 78 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 132 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 91 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 70 "Iris-virginica" "Iris-versicolor" 0 0 1
0 ? 129 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 72 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 99 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 42 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 96 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 83 "Iris-virginica" "Iris-versicolor" 0 0 1
0 ? 138 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 115 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 67 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 34 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 135 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 4 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 46 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 123 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 26 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 29 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 88 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 25 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 5 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 102 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 14 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 146 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 61 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 68 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 140 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 84 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 124 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 15 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 74 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 41 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 71 "Iris-versicolor" "Iris-versicolor" 0 1 0
0 ? 22 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 27 "Iris-setosa" "Iris-setosa" 1 0 0
0 ? 128 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 113 "Iris-virginica" "Iris-virginica" 0 0 1
0 ? 73 "Iris-versicolor" "Iris-versicolor" 0 1 0

**Comment by jakobbossek** [comment]
Obviously the arff is malformed. The arff format uses comma to separate data instead of whitespace.

**Comment by jakobbossek** [comment]
Does the server check for the validity of uploaded arff files? Obviously not.

**Comment by giuseppec** [comment]
did you update your farff? I fixed this in january https://github.com/mlr-org/farff/commit/db21d3a268ad4438a2c7042006bbc92fd540d1fa

**Comment by jakobbossek** [comment]
I do not know who of you produced this run. I have installed the current version.

**Comment by berndbischl** [comment]
we need to do 2 things:
a) run arffs need be checked on upload on the server
b) in OML R we need a unit test that we can parse a produced run arff

**Comment by berndbischl** [comment]
closing, we have new issues for this which are more precise
