### ISSUE TITLE
writeARFF is slow

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/farff#5]
is there a faster writer for table data that we can use?
fwrite does not exist, and will not be written.
maybe in readr?

**Comment by jakobbossek** [comment]
Possibly helpful:
* http://stackoverflow.com/questions/9703068/most-efficient-way-of-exporting-large-3-9-mill-obs-data-frames-to-text-file
* https://github.com/Rdatatable/data.table/issues/580

**Comment by jakobbossek** [comment]
We chunk stuff now before writing for data frames with > 1e6 (by default) rows.
Closing for now.
